### ISSUE TITLE
Provide copy&paste for developing operators tutorial

### ISSUE THREAD

**Issue by alenkacz** [kudobuilder/kudo.dev#97]
**What would you like to be added**:
As requested here
https://github.com/kudobuilder/www/pull/84/files#r346814591

**Why is this needed**:

**Comment by kensipe** [comment]
The getting started was overhauled during docathon week and we created runbooks which has a tutorial 
https://kudo.dev/docs/runbooks/admin/create-operator.html#preconditions

@alenkacz do you specifically mean that the website should have a copy button?  it doesn't have that currently but otherwise meets the needs here.   Please reopen if more is desired.
